### ISSUE TITLE
script do not work on reboot

### ISSUE THREAD

**Issue by franke2** [cpriest/udm-patches#5]
Hi, tnx for your excellent script.
I'm trying to use your script with openvpn client.
i have installed  on-boot-script and I have activated your script.
All is working fine but if I reboot the router it does not work correctly...
on the openvpn log I can read that sequence is completed but I'm not able to ping any remote subnet...
after 120 sec I receive a ping reset and openvpn restart... no way to let it work...
if I reinstall on-boot-script and reactivate auth.sh and openvpn.sh all is working fine.
What I'm doing wrong?
Tnx for help

**Comment by cpriest** [comment]
I have had occasions where on reboot the openvpn connection is started by the UDM prior to the onboot scripts running.  When that happens, I just go in and disable the VPN connection and then go in and re-enable it.

Let me know if that works, if so then having the openvpn onboot script look for existing VPN processes already running and killing them would probably take care of that boot problem.

**Comment by franke2** [comment]
hi, tnt for your answer
i restarted the udm and openvpn was started (also the client script) but is not working.
`TUN/TAP device tun1 opened                                                   
Mon Feb  8 22:32:39 2021 do_ifconfig, tt->did_ifconfig_ipv6_setup=0                                   
Mon Feb  8 22:32:39 2021 /usr/sbin/ip link set dev tun1 up mtu 1500                                   
Mon Feb  8 22:32:39 2021 /usr/sbin/ip addr add dev tun1 10.1.2.40/24 broadcast 10.1.2.255             
Mon Feb  8 22:32:39 2021 /mnt/data/udm-patches/scripts/openvpn-notify.sh up 1 tun1 1500 1553 10.1.2.40 255.255.255.0 init
Mon Feb  8 22:32:39 2021 Initialization Sequence Completed                                                               
Mon Feb  8 22:34:40 2021 [CLOUD] Inactivity timeout (--ping-restart), restarting                                         
Mon Feb  8 22:34:40 2021 /mnt/data/udm-patches/scripts/openvpn-notify.sh down 1 tun1 1500 1553 10.1.2.40 255.255.255.0 restart
Mon Feb  8 22:34:40 2021 SIGUSR1[soft,ping-restart] received, process restarting                                              
Mon Feb  8 22:34:45 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts`

i tryed to disable vpn on udm gui and then enable it... but it is not working... I need to reinstall unboot script... I think I'm missing some :(
any suggestion?

**Comment by franke2** [comment]
just an update... to restart the script I tryed to disable openvpn on udm gun, restarted the udm and then enable openvpn...
it worked... 
Can you tell me how to solve it?
is possible to have openvpn client working on reboot?

**Comment by cpriest** [comment]
This is your problem:

```
Mon Feb  8 22:34:40 2021 [CLOUD] Inactivity timeout (--ping-restart), restarting   
```

Something in the config is causing an inactivity timeout, this is either being pushed down from the VPN server to you, or it's in your local config.  You can set up your local client to ping every minute to avoid the timeout.
