### ISSUE TITLE
UDMP not responding after reboot

### ISSUE THREAD

**Issue by djrm05** [cpriest/udm-patches#7]
After the installation and configuration as described, the vpn tunnel is up and seems that works properly, however just trying to reboot the UDMP it boot, but it is not longer reachable. Trying to ping the UDMP result in really intermitent responses with lot of lost pings.
The only way I have found to get access to the UDMP is to factory reset and restore backup. 
I have made 3 attempts and the outcome is always the same. Have you seen this before?
UDMP running 1.9.3-1
Only 1 vpn configured (same vpn configuration in an ubuntu machine works without issues)
WAN PPoE connection

Any help would be appreciated as I would like to use this fantastic workaround for the vpn client.

Thank you

**Comment by cpriest** [comment]
Hmm, what happens if you do the above but only install the on_boot setup?  

There's really nothing in this project, that I'm aware of, that would cause it to fail to come back up after a reboot.  The reality is that this really just replaces the openvpn binary with a script to intercept the calls from UDMP.

**Comment by djrm05** [comment]
Just installing the on_boot setup the UDMP boot normally. I have tried to reboot the UDMP after disabling the vpn network as well and again I lost it  on boot.
I don't know what else could I try really.

**Comment by djrm05** [comment]
Hi @cpriest 
So I have been playing with this trying to understand why this issue is happening. So I followed the below scenario.

I moved openvpn.sh out from on_boot.d folder to udm-patches. Then configured everything, the vpn tunnel was up and then rebooted the UDMP.  After reboot the UDMP is reachable as normal, but obviously vpn is down, so just established a ssh session and started openvpn.sh. The vpn tunnel was established as expected and network remains reachable.
I then created a new sh file in on_boot.d folder with a simple "sleep 1m" before to call your openvpn.sh and then all work! :)
So it seems that for any reason openvpn.sh is interrupting the normal UDMP network boot process and leaving some time to allow the network up before run the script, the issue gone.

Any thought on this?

Thanks

**Comment by steierc** [comment]
@cpriest , I am also having this issue.
i have followed the workaround provided by @djrm05 and this seems to have "worked around" the issue however a cleaner solution may be better. 
It may not be obvious to other using the VPN Tunnel functionality, and they will be seeing non responsive UDMP's on reboot or when they systems come back online after a power failure.

**Comment by cpriest** [comment]
Hmm, interesting.  I could see that solving some issues if the UDMP was trying to do more w/ openvpn at startup that I had not realized was happening and my script trouncing all over that.

Seems adding a simple wait in there should be sufficient to avoid that issue.

**Comment by cpriest** [comment]
Does the above change match what you've done?

**Comment by djrm05** [comment]
Yes, this is what i did. However I think that it would be better to understand what need to be up before run the script and perform the right check to avoid just a simple sleep (this should be a workaround only) which could vary from one device to other.

I still checking on my side what could be used to evaluate if the script can run safely, as Im not confident at all about the sleep.....

**Comment by cpriest** [comment]
Hmm, what is the linkcheck/connected file representing?  

Does that 1 correspond to the openvpn-**1** part?

**Comment by djrm05** [comment]
As far as I have seen this is to set a variable to 1 or 0 for internet
connected or disconnected. By the way I added this to the on boot script
and have tested with lot of reboots and everything have worked properly.

**Comment by cpriest** [comment]
ok cool.  I'll revert that last change I made, could you submit a PR w/ the changes?

**Comment by djrm05** [comment]
done :)

**Comment by cpriest** [comment]
Nice, thanks for the contribution #8
